import flowbite from "flowbite/plugin";

export default {
    darkMode: 'class',
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./node_modules/flowbite/**/*.js",
    ],
    theme: {
        extend: {
            colors: {
              "on-tertiary-container": "#f3fffe",
              "outline-variant": "#c1c6d7",
              "tertiary-fixed": "#d4e6e5",
              "primary-fixed": "#d8e2ff",
              "surface-dim": "#d8dadc",
              "on-secondary-container": "#00705e",
              "background": "#f7f9fb",
              "surface-container-low": "#f2f4f6",
              "on-tertiary-fixed": "#0e1e1e",
              "surface-container-lowest": "#ffffff",
              "error": "#ba1a1a",
              "on-secondary-fixed-variant": "#005143",
              "tertiary-fixed-dim": "#b8cac9",
              "secondary-container": "#54f8d7",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#3a4a49",
              "on-tertiary": "#ffffff",
              "tertiary-container": "#677877",
              "tertiary": "#4f5f5f",
              "surface-container": "#eceef0",
              "surface-container-high": "#e6e8ea",
              "surface": "#f7f9fb",
              "primary-fixed-dim": "#adc6ff",
              "on-secondary": "#ffffff",
              "inverse-primary": "#adc6ff",
              "on-primary": "#ffffff",
              "secondary-fixed": "#58fbda",
              "primary": "#0058bc",
              "on-secondary-fixed": "#00201a",
              "surface-variant": "#e0e3e5",
              "inverse-on-surface": "#eff1f3",
              "surface-tint": "#005bc1",
              "on-background": "#191c1e",
              "surface-bright": "#f7f9fb",
              "outline": "#717786",
              "secondary-fixed-dim": "#2cdebf",
              "secondary": "#006b5a",
              "inverse-surface": "#2d3133",
              "on-primary-container": "#fefcff",
              "on-surface-variant": "#414755",
              "on-surface": "#191c1e",
              "on-primary-fixed": "#001a41",
              "on-error-container": "#93000a",
              "on-error": "#ffffff",
              "primary-container": "#0070eb",
              "on-primary-fixed-variant": "#004493",
              "surface-container-highest": "#e0e3e5"
            },
            fontFamily: {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
        },
    },
    plugins: [
        flowbite,
    ],
};
